version: '3'

volumes:
  postgres_database:

services:
  table-client-app:
    image: freeezzz/table-client-app
    restart: always
    ports:
      - 3000:3000
  table-server-app:
    image: freeezzz/table-server-app
    restart: always
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
  postgres:
    image: postgres:latest
    volumes:
      - postgres_database:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apptable
